import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: "100vh",
    background: "#F7F5F0",
    color: "#1F2421",
    fontFamily: "'Inter', system-ui, sans-serif",
    paddingBottom: 40,
  },
  loadingWrap: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F7F5F0",
    color: "#1F2421",
  },
  header: {
    background: "#1F2421",
    borderBottom: "3px solid #FF5A1F",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerInner: {
    maxWidth: 960,
    margin: "0 auto",
    padding: "16px 20px 0 20px",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    marginBottom: 14,
  },
  logo: {
    fontFamily: "'Space Grotesk', 'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 22,
    letterSpacing: "-0.02em",
  },
  logoA: { color: "#F7F5F0" },
  logoB: { color: "#FF5A1F" },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
  },
  headerStat: {
    fontSize: 12,
    fontWeight: 600,
    color: "#F7F5F0",
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 100,
    padding: "4px 12px",
    whiteSpace: "nowrap",
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    background: "#FF5A1F",
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  signInBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "#F7F5F0",
    borderRadius: 100,
    padding: "7px 14px",
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  tabs: { display: "flex", gap: 4 },
  tabBtn: {
    background: "none",
    border: "none",
    borderBottom: "3px solid transparent",
    color: "#9B9B94",
    fontSize: 14,
    fontWeight: 600,
    padding: "0 4px 12px 4px",
    marginRight: 20,
  },
  tabBtnActive: {
    color: "#F7F5F0",
    borderBottomColor: "#FF5A1F",
  },
  main: {
    maxWidth: 960,
    margin: "0 auto",
    padding: "20px 16px 100px 16px",
  },
  filterRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 20,
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    border: "1.5px solid #DEDAD0",
    background: "#fff",
    color: "#4A4A44",
    borderRadius: 100,
    padding: "6px 14px",
    fontSize: 13,
    fontWeight: 600,
  },
  chipActive: {
    background: "#1F2421",
    color: "#F7F5F0",
    borderColor: "#1F2421",
  },
  chipCount: {
    background: "#EFE9DE",
    color: "#1F2421",
    borderRadius: 100,
    padding: "1px 7px",
    fontSize: 11,
    fontWeight: 700,
  },
  chipCountOn: {
    background: "rgba(255,255,255,0.2)",
    color: "#F7F5F0",
  },
  empty: {
    textAlign: "center",
    padding: "64px 20px",
    border: "1.5px dashed #DEDAD0",
    borderRadius: 14,
    background: "#FBFAF6",
  },
  emptyTitle: {
    fontWeight: 700,
    fontSize: 16,
    margin: "0 0 6px 0",
  },
  emptySub: {
    fontSize: 13.5,
    color: "#7A7A72",
    margin: "0 0 18px 0",
  },
  emptyCta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#1F2421",
    color: "#F7F5F0",
    border: "none",
    borderRadius: 10,
    padding: "11px 18px",
    fontSize: 13.5,
    fontWeight: 600,
  },
  grid: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  card: {
    background: "#fff",
    border: "1.5px solid #EAE6DC",
    borderRadius: 14,
    padding: "16px 18px",
    position: "relative",
    cursor: "pointer",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  iconWrap: {
    width: 30,
    height: 30,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  price: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 19,
    letterSpacing: "-0.01em",
  },
  cardTitle: {
    fontSize: 15.5,
    fontWeight: 700,
    margin: "0 0 4px 0",
    lineHeight: 1.3,
  },
  cardNote: {
    fontSize: 13,
    color: "#6B6B63",
    margin: "0 0 12px 0",
    lineHeight: 1.45,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  metaRow: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  metaItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "#8A8A82",
  },
  cardFoot: {
    borderTop: "1px dashed #EAE6DC",
    paddingTop: 12,
    display: "flex",
    justifyContent: "flex-end",
  },
  claimBtn: {
    background: "#1F2421",
    color: "#F7F5F0",
    border: "none",
    borderRadius: 9,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
  },
  claimedTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 700,
    color: "#2E5F5B",
    background: "#E4EEE9",
    padding: "6px 12px",
    borderRadius: 8,
  },
  formWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  label: {
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "#7A7A72",
    marginTop: 14,
    marginBottom: 6,
  },
  input: {
    border: "1.5px solid #DEDAD0",
    borderRadius: 11,
    padding: "12px 14px",
    fontSize: 14.5,
    background: "#fff",
    outline: "none",
    color: "#1F2421",
    width: "100%",
  },
  catGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  catBtn: {
    border: "1.5px solid #DEDAD0",
    borderRadius: 11,
    padding: "10px 8px",
    fontSize: 13,
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
    background: "#fff",
    color: "#1F2421",
  },
  twoCol: { display: "flex", gap: 12 },
  formActions: { display: "flex", gap: 10, marginTop: 24 },
  cancelBtn: {
    flex: 1,
    background: "#fff",
    color: "#4A4A44",
    border: "1.5px solid #DEDAD0",
    borderRadius: 11,
    padding: "14px 18px",
    fontSize: 15,
    fontWeight: 600,
  },
  postBtn: {
    flex: 1.6,
    background: "#FF5A1F",
    color: "#fff",
    border: "none",
    borderRadius: 11,
    padding: "14px 18px",
    fontSize: 15,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  formFoot: {
    fontSize: 12,
    color: "#9B9B94",
    textAlign: "center",
    marginTop: 10,
  },
  posterP: {
    fontSize: 12.5,
    color: "#7A7A72",
    margin: "0 0 6px 0",
  },
  fab: {
    position: "fixed",
    bottom: 24,
    right: 24,
    width: 54,
    height: 54,
    borderRadius: "50%",
    background: "#FF5A1F",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 6px 18px rgba(255,90,31,0.4)",
  },
  toast: {
    position: "fixed",
    bottom: 24,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#1F2421",
    color: "#F7F5F0",
    padding: "10px 18px",
    borderRadius: 100,
    fontSize: 13,
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    maxWidth: "calc(100vw - 32px)",
  },
  modalHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  modalTitle: {
    fontFamily: "'Space Grotesk', 'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 18,
    margin: 0,
  },
  iconBtn: {
    background: "#F3F0E8",
    border: "none",
    width: 30,
    height: 30,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#4A4A44",
    flexShrink: 0,
  },
  detailTop: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 14,
  },
  detailChip: {
    fontSize: 12,
    fontWeight: 700,
    padding: "5px 11px",
    borderRadius: 100,
    border: "1.5px solid",
  },
  detailPrice: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 28,
    letterSpacing: "-0.02em",
    margin: "0 0 2px 0",
  },
  detailTitle: {
    fontSize: 16.5,
    fontWeight: 700,
    margin: "0 0 12px 0",
    lineHeight: 1.35,
  },
  detailMeta: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    marginBottom: 16,
  },
  detailNote: {
    background: "#F7F5F0",
    border: "1px solid #EAE6DC",
    borderRadius: 12,
    padding: "14px 16px",
    fontSize: 14,
    color: "#3A3F3B",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    marginBottom: 22,
  },
  detailAction: {
    display: "flex",
    justifyContent: "flex-end",
  },
  detailClaimBtn: {
    background: "#FF5A1F",
    color: "#fff",
    border: "none",
    borderRadius: 11,
    padding: "12px 22px",
    fontSize: 14.5,
    fontWeight: 700,
  },
  claimedBig: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "#2E5F5B",
    background: "#E4EEE9",
    borderRadius: 11,
    padding: "12px 22px",
    fontWeight: 700,
    fontSize: 14.5,
  },
  primaryBtn: {
    width: "100%",
    marginTop: 18,
    background: "#1F2421",
    color: "#F7F5F0",
    border: "none",
    borderRadius: 11,
    padding: "13px",
    fontSize: 15,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  switchBtn: {
    background: "none",
    border: "none",
    color: "#FF5A1F",
    fontWeight: 600,
    fontSize: 13.5,
    marginTop: 14,
    width: "100%",
    textAlign: "center",
    padding: 0,
  },
  hint: {
    fontSize: 11.5,
    color: "#9B9B94",
    textAlign: "center",
    marginTop: 12,
    marginBottom: 0,
  },
  formError: {
    color: "#B33A2B",
    background: "#FBE9E5",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13,
    fontWeight: 600,
    marginTop: 14,
    marginBottom: 0,
  },
  settingEmail: {
    fontSize: 12.5,
    color: "#7A7A72",
    margin: "0 0 4px 0",
  },
  settingRow: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    padding: "12px 0",
  },
  settingLabel: {
    margin: 0,
    fontWeight: 700,
    fontSize: 14,
    color: "#1F2421",
  },
  settingDesc: {
    margin: "2px 0 0 0",
    fontSize: 12.5,
    color: "#7A7A72",
  },
  toggle: {
    width: 42,
    height: 24,
    borderRadius: 999,
    border: "1.5px solid #DEDAD0",
    background: "#E9E5DB",
    position: "relative",
    flexShrink: 0,
    padding: 0,
  },
  toggleOn: {
    background: "#FF5A1F",
    borderColor: "#FF5A1F",
  },
  toggleKnob: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    display: "block",
    transform: "translateX(2px)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.25)",
  },
  toggleKnobOn: {
    transform: "translateX(20px)",
  },
  divider: {
    borderTop: "1px solid #EAE6DC",
    margin: "14px 0",
  },
  dangerBtn: {
    width: "100%",
    background: "#fff",
    color: "#B33A2B",
    border: "1.5px solid #F2D4CE",
    borderRadius: 10,
    padding: "11px",
    fontWeight: 600,
    fontSize: 13.5,
    marginTop: 8,
  },
  dangerBtnSoft: {
    width: "100%",
    background: "#1F2421",
    color: "#F7F5F0",
    border: "none",
    borderRadius: 10,
    padding: "11px",
    fontWeight: 600,
    fontSize: 13.5,
    marginTop: 8,
  },
  hero: {
    background: "linear-gradient(135deg, #1F2421 0%, #2A2F2B 55%, #3A2E24 100%)",
    borderRadius: 16,
    padding: "20px 22px",
    display: "flex",
    alignItems: "center",
    gap: 16,
    justifyContent: "space-between",
    flexWrap: "wrap",
    marginBottom: 20,
    border: "1px solid #2E332F",
    overflow: "hidden",
  },
  heroEyebrow: {
    margin: 0,
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#FF5A1F",
  },
  heroTitle: {
    margin: "4px 0 4px 0",
    fontFamily: "'Space Grotesk', 'Inter', sans-serif",
    fontSize: 22,
    lineHeight: 1.2,
    color: "#F7F5F0",
    fontWeight: 700,
    maxWidth: 460,
  },
  heroSub: {
    margin: 0,
    fontSize: 13,
    color: "#B9B9B0",
  },
  heroCta: {
    background: "#FF5A1F",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "11px 16px",
    fontSize: 13.5,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  levelPill: {
    fontSize: 11,
    fontWeight: 800,
    color: "#FF5A1F",
    border: "1.5px solid rgba(255,90,31,0.5)",
    borderRadius: 100,
    padding: "3px 8px",
    whiteSpace: "nowrap",
    background: "rgba(255,90,31,0.08)",
  },
  cardCat: {
    fontSize: 11.5,
    fontWeight: 700,
  },
  xpBox: {
    background: "#F7F5F0",
    border: "1px solid #EAE6DC",
    borderRadius: 12,
    padding: "14px",
    margin: "10px 0 4px 0",
  },
  xpBar: {
    height: 8,
    borderRadius: 999,
    background: "#E6E1D6",
    overflow: "hidden",
    marginTop: 8,
  },
  xpFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #FF5A1F, #FF8A4C)",
  },
  ownerTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 700,
    color: "#4A4A44",
    background: "#EFEAE0",
    padding: "6px 12px",
    borderRadius: 8,
  },
  markCompleteBtn: {
    background: "#2E5F5B",
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 600,
  },
  detailMarkBtn: {
    background: "#2E5F5B",
    color: "#fff",
    border: "none",
    borderRadius: 11,
    padding: "12px 22px",
    fontSize: 14.5,
    fontWeight: 700,
  },
  completeTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 700,
    color: "#5C7A3D",
    background: "#E9F0E0",
    padding: "6px 12px",
    borderRadius: 8,
  },
  adBanner: {
    border: "1.5px dashed #CFC9BC",
    borderRadius: 14,
    background: "#F1EEE6",
    padding: "14px 16px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  adBadge: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.1em",
    color: "#8A8A82",
    border: "1px solid #CFC9BC",
    borderRadius: 4,
    padding: "2px 6px",
    flexShrink: 0,
  },
  adTitle: {
    margin: 0,
    fontSize: 14.5,
    fontWeight: 700,
    color: "#5A5A52",
  },
  adText: {
    margin: "2px 0 0 0",
    fontSize: 12.5,
    color: "#8A8A82",
  },
  adCard: {
    border: "1.5px dashed #CFC9BC",
    borderRadius: 14,
    background: "#F1EEE6",
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
    justifyContent: "center",
    minHeight: 120,
  },
  adDisclaimer: {
    fontSize: 11.5,
    color: "#9B9B94",
    margin: "18px 0 0 0",
    textAlign: "center",
  },
  promotedTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.02em",
    color: "#FF5A1F",
    background: "rgba(255,90,31,0.12)",
    border: "1px solid rgba(255,90,31,0.35)",
    borderRadius: 100,
    padding: "3px 8px",
    whiteSpace: "nowrap",
  },
  promoRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 18,
    background: "#FBFAF6",
    border: "1px solid #EAE6DC",
    borderRadius: 12,
    padding: "12px 14px",
    cursor: "pointer",
  },
  promoCheck: {
    marginTop: 2,
    accentColor: "#FF5A1F",
    width: 18,
    height: 18,
    flexShrink: 0,
  },
  promoLabel: {
    fontSize: 14,
    fontWeight: 700,
    color: "#1F2421",
  },
  promoDesc: {
    display: "block",
    fontSize: 12.5,
    color: "#7A7A72",
    marginTop: 2,
  },
  checkoutSummary: {
    background: "#F7F5F0",
    border: "1px solid #EAE6DC",
    borderRadius: 12,
    padding: "14px 16px",
    marginBottom: 4,
  },
  checkoutTitle: {
    margin: 0,
    fontSize: 14.5,
    fontWeight: 700,
    color: "#1F2421",
  },
  checkoutMeta: {
    margin: "4px 0 0 0",
    fontSize: 12.5,
    color: "#7A7A72",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  },
  checkoutTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    padding: "12px 0",
    borderTop: "1px dashed #EAE6DC",
    fontSize: 14,
    color: "#4A4A44",
  },
  promoBtn: {
    background: "#1F2421",
    color: "#F7F5F0",
    border: "none",
    borderRadius: 10,
    padding: "11px 16px",
    fontSize: 13.5,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  promoHint: {
    margin: "6px 0 0 0",
    fontSize: 11.5,
    color: "#9B9B94",
  },
  detailPromo: {
    marginTop: 18,
    borderTop: "1px dashed #EAE6DC",
    paddingTop: 16,
  },
};